### ISSUE TITLE
switching between wasd and arrow keys for movement inputs

### ISSUE THREAD

**Issue by SyMunshine** [SyMunshine/group-project-comp55-resurrected#3]
As a player
I want to have the flexibility of using wasd or the arrow keys to control my character
so that in the event that I don't have arrow keys i can use wasd to control my character. 

This issue is aimed at making the game more flexible for the player, but also aimed at fixing a bug where using non arrow keys causes the character to freeze and completely refuse input, possibly caused by poor error handling in the player movement function. additionally, there is the chance to rewrite the function so that it is more generalized and smoother to move, rather than it's current clunky state.

**Comment by onzfonz** [comment]
OK so would it be any keys? Can that setting be somehow changed so that they could use any keys?

**Comment by SyMunshine** [comment]
This could be generalized into creating a separate pane in the settings where you can check the keybinds and set them to whichever key you'd like to make the game more accessible to people

**Comment by onzfonz** [comment]
Ok sounds good to me 🚀

**Comment by SyMunshine** [comment]
Steps to use this feature:
1. Open the Client
2. Click on Settings
3. Click on Keybinds
**Begin Confusing section**
4. Press the key you want to replace the existing key
5. Click on Change (Up / Down / Left / Right) Keybind button
6. The label corresponding to the direction located in the middle of the application should change to the key you've selected
7. Repeat 4,5,6 for other keybinds
**End Confusing section**
8. Click on Back button to return to settings
9. Click on Back button to return to main menu
10. Click on Play button to begin playing with new keybinds. 


Unfortunately I wasn't able to figure out how to have it so that you can 
1. Click on Change [directional] Keybind
2. Wait for keyboard input
3. Press a key for new keybind
4. Set keybind and update label to new keybind
